export type WordTier = 'easy' | 'medium' | 'hard' | 'expert'

export const WORD_POOLS: Record<WordTier, string[]> = {
  easy: [
    'at', 'be', 'by', 'do', 'go', 'he', 'if', 'in', 'is', 'it',
    'me', 'my', 'no', 'of', 'on', 'or', 'so', 'to', 'up', 'us',
    'we', 'cat', 'dog', 'sun', 'run', 'fly', 'sky', 'sea', 'hit',
    'win', 'map', 'top', 'red', 'hot', 'big', 'old', 'new', 'far',
    'arm', 'arc', 'aim', 'ace', 'add', 'age', 'ago', 'aid', 'air',
    'all', 'and', 'any', 'ape', 'apt', 'art', 'ask', 'awe', 'axe',
    'bad', 'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bet', 'bit',
    'bow', 'box', 'boy', 'bud', 'bug', 'bun', 'bus', 'but', 'buy',
    'cab', 'can', 'cap', 'car', 'cob', 'cod', 'cog', 'cop', 'cot',
    'cow', 'cry', 'cup', 'cut', 'dab', 'dam', 'dew', 'did', 'dig',
    'dim', 'dip', 'dot', 'dry', 'dub', 'dug', 'duo', 'dye', 'ear',
    'eat', 'egg', 'ego', 'elf', 'elm', 'end', 'era', 'eve', 'eye',
    'fan', 'fat', 'fee', 'few', 'fig', 'fin', 'fit', 'fix', 'fog',
    'for', 'fox', 'fry', 'fun', 'fur', 'gap', 'gas', 'gel', 'gem',
    'get', 'gig', 'gin', 'gnu', 'got', 'gum', 'gun', 'gut', 'guy',
    'gym', 'had', 'ham', 'has', 'hat', 'hay', 'her', 'hid', 'him',
    'hip', 'his', 'hog', 'hop', 'how', 'hub', 'hue', 'hug', 'hum',
    'ice', 'icy', 'ill', 'imp', 'ink', 'inn', 'ion', 'ire', 'ivy',
    'jab', 'jag', 'jam', 'jar', 'jaw', 'jay', 'jet', 'jot', 'joy',
    'jug', 'jut', 'keg', 'key', 'kid', 'kin', 'kit', 'lab', 'lag',
  ],
  medium: [
    'alpha', 'bravo', 'delta', 'echo', 'foxtrot', 'gamma', 'hotel',
    'laser', 'orbit', 'pilot', 'radar', 'solar', 'storm', 'thrust',
    'venus', 'warp', 'xenon', 'yield', 'zephyr', 'comet', 'crater',
    'debris', 'engine', 'galaxy', 'impact', 'junior', 'kernel',
    'meteor', 'nebula', 'oxygen', 'photon', 'quasar', 'rocket',
    'shield', 'signal', 'sector', 'target', 'turret', 'vector',
    'weapon', 'zenith', 'anchor', 'beacon', 'cannon', 'capsule',
    'charge', 'chrome', 'cipher', 'cluster', 'combat', 'conduit',
    'cortex', 'cosmos', 'driven', 'dynamo', 'energy', 'falcon',
    'fusion', 'glitch', 'gunner', 'hunter', 'ignite', 'inferno',
    'jumper', 'kelvin', 'launch', 'legion', 'matrix', 'nitro',
    'plasma', 'proton', 'pulsar', 'raptor', 'reaper', 'reflex',
    'relay', 'runner', 'sensor', 'shadow', 'shard', 'sniper',
    'specter', 'sphere', 'sprint', 'static', 'stealth', 'strike',
    'strobe', 'surge', 'swift', 'synapse', 'tether', 'titan',
    'torque', 'tracer', 'trigger', 'turbo', 'typhoon', 'uplink',
    'valve', 'vault', 'vigor', 'viral', 'vortex', 'warden', 'warhead',
    'hazard', 'hybrid', 'hyper', 'inert', 'ionic', 'isobar', 'isotope',
    'jammer', 'jetpack', 'kevlar', 'kinetic', 'laser', 'lancer',
    'linker', 'liquid', 'loader', 'magnet', 'mancer', 'marine',
    'marker', 'maser', 'module', 'mortar', 'motive', 'munition',
    'neuron', 'nexus', 'nodule', 'nomad', 'novice', 'nozzle',
    'oblique', 'offset', 'onyx', 'optic', 'oracle', 'outpost',
    'output', 'overload', 'packet', 'patrol', 'payload', 'phoenix',
    'photon', 'plexus', 'portal', 'prism', 'probe', 'propel',
    'pulse', 'quarry', 'ramjet', 'ranger', 'recon', 'redirect',
    'refuel', 'reload', 'remote', 'repeat', 'reset', 'resist',
    'retro', 'revolt', 'reward', 'ricochet', 'rifle', 'rift',
    'ripple', 'rival', 'rotor', 'round', 'router', 'rupture',
    'salvo', 'scalar', 'scan', 'scope', 'scout', 'scramble',
    'screen', 'seeker', 'servo', 'silo', 'solar', 'sonar',
    'sortie', 'source', 'spark', 'spawn', 'spire', 'splice',
    'spool', 'squad', 'stable', 'stalker', 'strafe', 'stream',
    'stun', 'subunit', 'supply', 'swarm', 'switch', 'symbol',
    'system', 'tactical', 'tank', 'tape', 'task', 'telemetry',
    'tempo', 'tensor', 'terminal', 'terrain', 'thermal', 'token',
    'trace', 'track', 'transit', 'trauma', 'tremor', 'trident',
    'tripwire', 'turret', 'unit', 'uplink', 'urgent', 'utility',
  ],
  hard: [
    'algorithm', 'bandwidth', 'collision', 'diffusion', 'encrypted',
    'framework', 'gigabyte', 'hyperdrive', 'interface', 'javascript',
    'kilowatt', 'launchpad', 'magnitude', 'navigation', 'oscillate',
    'parallax', 'quantum', 'recursion', 'singularity', 'telescope',
    'ultraviolet', 'velocity', 'wavelength', 'xenolith', 'yottabyte',
    'typescript', 'spacecraft', 'atmospheric', 'exploration', 'trajectory',
    'acceleration', 'antimatter', 'blackhole', 'calibration', 'detonator',
    'electrodes', 'frequency', 'gravitation', 'heatseeker', 'intercept',
    'jettison', 'kinematic', 'lockdown', 'mainframe', 'neutralize',
    'overcharge', 'perimeter', 'quickstrike', 'retaliate', 'scrambler',
    'shockwave', 'simulator', 'stratosphere', 'supernova', 'targeting',
    'technocrat', 'terminate', 'threshold', 'turbulence', 'wormhole',
    'aberration', 'abnormal', 'abrasion', 'absolute', 'abstraction',
    'abundance', 'abyss', 'accelerate', 'accurate', 'acidic',
    'acoustic', 'activate', 'adaptive', 'additive', 'adjacency',
    'adjuster', 'advanced', 'adversary', 'afterburn', 'aggregate',
    'aggressor', 'airborne', 'airframe', 'airstrike', 'algorithm',
    'alignment', 'allocate', 'altitude', 'amplifier', 'analyzer',
    'annihilate', 'aperture', 'approach', 'architect', 'armament',
    'armorclad', 'artillery', 'assailant', 'assassin', 'assembly',
    'assertion', 'asteroid', 'astral', 'attacker', 'augmented',
    'autopilot', 'auxiliary', 'avalanche', 'avoidance', 'barricade',
    'battalion', 'battleship', 'biometric', 'blackout', 'blastwave',
    'blockade', 'blueprint', 'boosters', 'boundary', 'breakpoint',
    'broadcast', 'bulkhead', 'camouflage', 'capacitor', 'cardinal',
    'carnage', 'cascading', 'catapult', 'celestial', 'centrifuge',
    'chainlink', 'channeled', 'checkpoint', 'chemical', 'chronicle',
    'circuitry', 'cloaking', 'coalesce', 'coherent', 'combatant',
    'commander', 'composite', 'compress', 'concealed', 'condenser',
    'conductor', 'configure', 'conquest', 'construct', 'containment',
    'continuum', 'converge', 'coolant', 'coordinate', 'core',
    'correlate', 'countermeasure', 'coverage', 'crossfire', 'cryptic',
    'datastream', 'decimate', 'deflector', 'detonation', 'deviate',
    'directive', 'discharge', 'dispersal', 'disruptor', 'dominance',
    'downlink', 'downrange', 'dragonskin', 'dropship', 'dualcore',
    'duplicate', 'duralumin', 'dynamics', 'efficiency', 'ejection',
    'eliminate', 'emitter', 'encoding', 'endurance', 'enforcer',
    'escalate', 'evasion', 'excavate', 'exchange', 'exhaust',
    'exosphere', 'expedite', 'explosive', 'exponent', 'exposure',
  ],
  expert: [
    'astrophysics', 'biomechanical', 'cryptography', 'decentralized',
    'electromagnetic', 'exoskeleton', 'extraterrestrial', 'gravitational',
    'hypervelocity', 'immunological', 'infrastructure', 'instantaneous',
    'intercontinental', 'interstellar', 'nanotechnology', 'neurological',
    'overclocked', 'photosynthesis', 'planetesimal', 'quantization',
    'radiotelescope', 'reconnaissance', 'semiconductor', 'stratospheric',
    'subterranean', 'superconductor', 'thermodynamics', 'transcontinental',
    'transmogrified', 'unprecedented', 'bioluminescence', 'circumnavigation',
    'crystallography', 'desynchronized', 'disintegration', 'electromagnetism',
    'encapsulation', 'hallucination', 'metamorphosis', 'multidimensional',
    'overcalibrated', 'parallelization', 'perpendicular', 'photovoltaic',
    'polarization', 'pressurization', 'reconfiguration', 'reverberation',
    'stratification', 'superimposition', 'thermosphere', 'ultrasonics',
    'unidirectional', 'volatilization', 'weightlessness', 'acceleration',
    'accomplishment', 'accountability', 'acknowledgement', 'acquisition',
    'administration', 'aforementioned', 'agglomeration', 'amalgamation',
    'amplification', 'annihilation', 'anthropogenic', 'approximation',
    'assassination', 'authentication', 'autocorrelation', 'axiomatically',
    'biochemistry', 'bioengineering', 'bioinformatics', 'biomagnetics',
    'biosignature', 'bombardment', 'breakthrough', 'bureaucratic',
    'calibrations', 'carbonaceous', 'categorically', 'causality',
    'centralization', 'characterization', 'chronological', 'circumference',
    'classification', 'collaboratively', 'combustibility', 'commandeering',
    'communication', 'compartmentalize', 'complementary', 'configuration',
    'conglomeration', 'consciousness', 'consolidation', 'contamination',
    'contextualize', 'contradiction', 'controllability', 'coordination',
    'counterattack', 'counterbalance', 'counterintelligence', 'decapitation',
    'decomposition', 'decontamination', 'defragmentation', 'deliberation',
    'dematerialized', 'demonstration', 'depressurization', 'desaturation',
    'determination', 'differentiation', 'disorientation', 'documentation',
    'electromagnetic', 'electrostatic', 'emancipation', 'encirclement',
    'enlightenment', 'entrepreneurial', 'environmental', 'equalization',
    'establishment', 'exfiltration', 'experimentation', 'extrapolation',
    'falsification', 'fortification', 'fragmentation', 'functionality',
    'generalization', 'geosynchronous', 'gravitational', 'groundbreaking',
    'hallucination', 'harmonization', 'hierarchical', 'homogenization',
    'hybridization', 'hyperextension', 'identification', 'illumination',
    'implementation', 'impossibility', 'improvisation', 'incapacitation',
    'incineration', 'incompatibility', 'indoctrination', 'infiltration',
    'initialization', 'instrumentation', 'interconnected', 'interoperability',
  ],
}

export function getWordPool(tier: WordTier): string[] {
  return WORD_POOLS[tier]
}

export function getTierForScore(score: number): WordTier {
  if (score < 10) return 'easy'
  if (score < 30) return 'medium'
  if (score < 70) return 'hard'
  return 'expert'
}